name: DevSecOps Pipeline

on: [push]

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Security Tools
        run: |
          pip install semgrep safety

      - name: Run Semgrep Scan
        run: semgrep --config=auto .

      - name: Run Dependency Scan
        run: safety check

      - name: Build Docker Image
        run: docker build -t devsecops-app .

      - name: Install Trivy
        run: |
       sudo apt-get update
       sudo apt-get install -y wget apt-transport-https gnupg lsb-release
       wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
       echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
       sudo apt-get update
       sudo apt-get install -y trivy
      - name: Scan Docker Image
        run: trivy image devsecops-app
